### PR TITLE
Use nativeImage.createFromPath if the icon name includes a /

### PR DESCRIPTION
**Pull request by jaevans**
Addresses #29, it's just a brain-dead attempt to see if the idea works. I'm completely open to better ideas for how to implement this.

### CODE REVIEW

**Comment by felixerdy** [comment]
I think this would work, I will check that later. Do you know what happens when the file doesn't exist @jaevans ? We should maybe catch that case.

Thanks for your contribution!

**Comment by jaevans** [comment]
Sorry I didn't get back to you, I was out of town. A quick test to use a non-existent file name simply led to the image disappearing. I didn't check the console to see if there were any errors logged, I'll check that after I get to work today.

**Comment by jaevans** [comment]
I checked again today and setting an invalid path just causes the icon to not appear. There is no log of an error on the console. I don't think there needs to be any checking around the existence of the image.

**Comment by felixerdy** [comment]
Alright, thank you! 👍

**Pull request merged**
