### PR TITLE
Update to use touchbar-registry

### PR DESCRIPTION
**Pull request by Xapphire13**
This change allows the `touchbar` package to work along side other packages that use the touchbar by coordinating through [`touchbar-registry`](https://atom.io/packages/touchbar-registry).

Toggle has been removed since the use-case no longer exists.

### CODE REVIEW

**Comment by felixerdy** [comment]
Thank you for your contribution! I'd love to merge your improvements but there are still two things:
- Do I manually need to install `touchbar-registry` or will it be installed automatically? I needed to install in manually in order to run your branch
- When e.g. modifying a TouchBar button label in the edit window, the button on the TouchBar itself updates really slow. Is there any way to update the label immediately (like it is now)?

**Comment by Xapphire13** [comment]
1. It should automatically install when installing this package (though I'm unsure if I have done the required steps for [atom-package-deps](https://www.npmjs.com/package/atom-package-deps) to do that. I will look into it a little more =]
2. The slowness is a tradeoff I opted for in this initial update to use the touchbar-registry. To fix it, we would need to re-write the way this package updates the buttons to maintain which button it's modifying and only change that button. Currently, when you change a button, the entire collection of buttons is persisted to config and then that config is read back, and transformed into buttons for the touch bar; the slowdown is due to `touchbar-registry` not having a batch API, so first each old button must be removed, then each new button must be added (one by one).

**Comment by Xapphire13** [comment]
[this commit](https://github.com/felixerdy/touchbar/pull/41/commits/09aa3cb08ac67b3a1c7b37d151d9778189de7f69) should fix the auto-install of the dependencies =]

**Comment by Xapphire13** [comment]
Closing due to lack of activity (and the fact I no longer use Atom)

**Pull request closed without merging**
